### ISSUE TITLE
Upgrade to Ubuntu 18.04 LTS?

### ISSUE THREAD

**Issue by pedrofurtado** [beevelop/docker-base#2]
@beevelop

**Comment by beevelop** [comment]
Thank you for the suggestion. As quite a lot of my images originate from this base image, I have to check the implications first. And this needs quite some time to test through roughly, but I'll keep it in mind for the upcoming releases.

**Comment by beruic** [comment]
@beevelop Could you perhaps just tag a `:xenial` or `:16.04` version of this image, and then make a `:bionic` or `18.04` and start upgrading one by one.

Xenial ends support April next year, and it is also not long until Ubuntu 20.04 ‘Focal Fossa’ is here. Having already upgraded to Bionic should give you an advantage when you upgrade again. I understand your worries, but if you pin your sub projects on a specific major version tag, you can upgrade them gradually. Also, the faster you put a new version out, the faster we (the users) will test. 

My own use case is that we use `beevelop/cordova` for building APKs, and Ubuntu Xenial contains an old `curl` package. This means that right now we can't upgrade the SSL config of our servers, because `curl` does not support TLSv1.3.
